### ISSUE TITLE
Newline separated handlers in json config only show first handler in Uchiwa

### ISSUE THREAD

**Issue by xyntrix** [sensu/uchiwa#712] opened 2017-08-28 21:23 UTC
In some of our check definitions we have handlers broken out as such:
```
                       "handlers": [
                                "foo",
                                "bar"
                        ],
```
In this case, "foo" will only show up in uchiwa when drilling into client -> checks -> check details.

If we structure the json for the check definition as such:
```
                       "handlers": [
                                "foo", "bar"
                        ],
```
.. then both handlers will display in Uchiwa.  This appears to be cosmetic only. 

Sensu version: 0.26.5-2
Uchiwa version: 0.25.2

Likely Uchiwa just needs to concatenate all the handlers into a single line (stripping line feeds).

**Comment by palourde** [comment] 2017-09-19 13:43
Hi @xyntrix, sorry for the delayed response, I was in vacation for the past few weeks!

Unfortunately I was unable to reproduce this issue. If I use the following check configuration:

```
"check_handlers": {
      "command": "return.rb -c 0",
      "handlers": [
        "foo",
        "bar"
      ],
      [...]
    }
```

I get the following result in Uchiwa:

![screen shot 2017-09-19 at 09 39 13](https://user-images.githubusercontent.com/4105580/30595242-a381e6ea-9d1e-11e7-9b75-fdc1ac8247dc.png)

I'm not sure what happen in your case but I would suggest to verify the Sensu API to make sure it display both handlers and fire up your browser console to see if there's any javascript error showing up.

Let me know if you find anything!

Thanks

**Comment by palourde** [comment] 2017-11-30 16:27
I'm closing this issue since we didn't received any responses.

If you are still facing this problem, please let us know with a comment and we'll be happy to reopen the issue.

Thanks!

**Closed by palourde** 2017-11-30 16:27 UTC
Labels: Bug
