### ISSUE TITLE
Check names with apostrophes or spaces cannot be silenced

### ISSUE THREAD

**Issue by pgporada** [sensu/uchiwa#701] opened 2017-07-13 18:17 UTC
We had a check named `whatever-check-for-the thing`, another accidently named `whatever-check-for-this-other'thing` and we started correctly receiving alerts for the checks. When we went to acknowledge the alerts, we found that Uchiwa would not let us silence them because of the names.

## Expected Behavior
To be able to silence the alert.

## Current Behavior
We can't silence the alert.

## Your Environment
* Uchiwa version used: uchiwa-0.25.2-1.x86_64
* Sensu version used: sensu-0.29.0-11.el7.x86_64
* Centos7

**Comment by palourde** [comment] 2017-07-17 17:34
Hi @pgporada,

According to [Sensu documentation](https://sensuapp.org/docs/1.0/reference/checks.html#check-names), a check name cannot contain special characters or spaces, such as `'`, which explains why Uchiwa is not able to create a silenced entry for this check.

Sensu client & server 0.29 should invalidate this check. Do you know how and when this check was created? You might have to delete the client so it can register again without that check if you are unable to delete it.

Thanks!
cc @portertech

**Comment by palourde** [comment] 2017-07-21 15:43
Seems like a duplicate of https://github.com/sensu/sensu/issues/1706.

I'll close this issue since it looks like a problem within Sensu!

**Closed by palourde** 2017-07-21 15:43 UTC
Labels: Sensu API

**Comment by pgporada** [comment] 2017-07-22 00:43
Thanks for digging in! I just returned from my honeymoon and have been afk!
