### ISSUE TITLE
send external results to sensu-api

### ISSUE THREAD

**Issue by irom77** [sensu/uchiwa#461] opened 2016-03-22 12:36 UTC
That below works in Sensu Enterprise Dashboard but not Uchiwa to post check directly to sensu server 

`curl -H "Content-Type: application/json" -X POST -d '{"name":"clientname","source":"targetname","status":2,"output":"results information"}' http://localhost:4567/results`

Should I see it in Uchiwa under a client with the name set in source ? I think it is very important, it can also include the handler(s) in a "handlers" parameter ("handlers": ["handler1","handler2"])

**Comment by calebhailey** [comment] 2016-05-24 22:28
@irom77 thank you for submitting this issue. We're not sure if we understand what the issue is here and/or if this would be an issue w/ Sensu or Uchiwa. Please let us know if you still need any help.

In the interim, please refer to the Sensu Results API documentation, here: https://sensuapp.org/docs/latest/api-results#results-post

**Comment by palourde** [comment] 2017-04-13 18:23
I'm closing this issue since we didn't received any responses.

If you are still facing this problem, please let us know with a comment and we'll be happy to reopen the issue.

Thanks!

**Closed by palourde** 2017-04-13 18:23 UTC
Labels: Documentation
