### ISSUE TITLE
Full check output truncated

### ISSUE THREAD

**Issue by jeffrean** [sensu/uchiwa#696] opened 2017-06-28 19:13 UTC
## Expected Behavior
the check output field should display full stdout or at least display the maximum amount of lines possible before truncating

## Current Behavior
it seems that whenever a check's output exceeds 10 or so lines, Uchiwa simply outputs the first line of stdout output and another line with '...' followed by nothing else, like so:

<img width="918" alt="screen shot 2017-06-28 at 12 04 45 pm" src="https://user-images.githubusercontent.com/16710553/27655768-582f1500-5bfb-11e7-97dc-fce6198b38b9.png">

## Possible Solution
do not limit the amount of lines represented in the check result or represent all possible lines before truncation

## Steps to Reproduce (for bugs)
1.created a system stats check which writes about 26 lines to stdout
2.checked uchiwa and check output only displayed first line and '...'

## Context
check output seems to be represented fine unless output is extensive this issue has persisted since installing uchiwa

## Your Environment
sensu clients are running on centos 7 VMs, sensu server running out of an Ubuntu docker container

* Uchiwa version used: 0.22
* Sensu version used: 0.29

**Comment by pgporada** [comment] 2017-07-13 18:33
Having a little expandable section to show the full log would be awesome. Especially if it functioned like a travis ci build log ala https://travis-ci.org/sensu/uchiwa/jobs/247140660

**Comment by jeffrean** [comment] 2017-07-13 21:09
agreed. I'm quite new to Uchiwa - does anyone know the document in the source code in which this truncation occurs? Even if an expandable output feature like Travis CI logs isn't on the immediate to-do list, I wouldn't think it would be that hard to toggle full output with a checkbox or add a config option. Any ideas?

**Comment by jothoma1** [comment] 2017-10-13 08:16
Hi,
@palourde i think it was working before.
I'm using graylog-plugin-sensu https://github.com/cvtienhoven/graylog-plugin-sensu
And it was working, see this picture from the author :
![image](https://user-images.githubusercontent.com/19167503/31536548-5f397bee-afff-11e7-91c5-edffadc2f5af.png)

It's really annoying because my users now can't see the full output and they can't click on the Graylog link
Thanks in advance
Johan

**Comment by palourde** [comment] 2017-10-19 15:52
Hi!

Have you tried to upgrade to the latest release of Uchiwa? A lot of work around truncating has been done since the 0.22 release.

Thanks

**Comment by jeffrean** [comment] 2017-10-19 16:16
Thank you for checking in! I actually left the company in which I was working on a project utilizing Uchiwa so I have not checked, but I am sure they have upgraded.

cheers,
Alex

**Comment by jothoma1** [comment] 2017-10-19 16:58
Hi,
Sorry but for me the issue is still here and i'm in the latest version....
Can you reopen ?

Le 19 oct. 2017 5:52 PM, "Simon Plourde" <notifications@github.com> a
écrit :

**Comment by jeffrean** [comment] 2017-10-20 07:09
Apologies, I will leave it open!

**Comment by IoanaStanescu** [comment] 2017-11-09 15:54
@jothoma1 Hello, 
I am not encountering these issues since I upgraded to Uchiwa **0.26.3** and Sensu 1.1.2 (also added **truncate_output:false** to my checks definitions). In case you have not upgraded, maybe an upgrade could help you.

**Comment by jothoma1** [comment] 2017-11-13 10:13
Hi @IoanaStanescu 
Thanks for your help, i also have Sensu 1.1.2 and Uchiwa 0.26.3
This behavior is with SensuAlarmCallback plugin for Graylog, i have a bug open here :
https://github.com/cvtienhoven/graylog-plugin-sensu/issues/4

**Comment by palourde** [comment] 2017-11-30 16:29
Hi @jothoma1,

I believe this issue might be related to https://github.com/sensu/uchiwa/issues/708 and a fix will be included in the 1.0.0 release, which should be available by the end of the week. If you still face a problem with this newer release, please open a new issue so we can take a deeper look.

Thanks!

**Closed by palourde** 2017-11-30 16:29 UTC
Labels: Feature
