### ISSUE TITLE
Iframes should be in an extra box like images

### ISSUE THREAD

**Issue by runningman84** [sensu/uchiwa#561] opened 2016-09-09 08:17 UTC
Please locate the iframes below like the images. Furthermore it would be cool if we coul define the width and height of the iframe box.

I would like to embed wiki pages to each check to give our ops team a direct runbook. Displaying only the first 3-4 lines is not enough there...

**Comment by josephholsten** [comment] 2016-09-12 22:56
duplicate of #360

**Closed** 2016-09-13 16:31 UTC
