### ISSUE TITLE
Columns overlapped

### ISSUE THREAD

**Issue by autumnw** [sensu/uchiwa#368] opened 2015-08-18 17:15 UTC
Hi,

I just tried the new uchiwa release V0.10.3. I really love the multiple user/role support!
But looks like the there are some problems on UI. For example, in clients page, If event output is long, the column "datacenter" and "sensu version" will be overlapped. On the specific client page, the 3 columns are even messed up.
<img width="1093" alt="screen shot 2015-08-18 at 10 09 25 am" src="https://cloud.githubusercontent.com/assets/2652627/9337103/0a917f62-4592-11e5-9272-e56c6686af0f.png">
<img width="1261" alt="screen shot 2015-08-18 at 10 09 12 am" src="https://cloud.githubusercontent.com/assets/2652627/9337104/0a9aa8f8-4592-11e5-8bca-b55c9a108593.png">

**Comment by hurrycaine** [comment] 2015-08-19 02:50
I saw the same thing with the read only user. The icons that disappear due to not having access to stash, causes everything shift to the left one spot but the columns keep the same width.

**Comment by palourde** [comment] 2015-08-20 19:12
Indeed, this issue only appears with a read-only user. Should be relatively easy to fix.

**Comment by autumnw** [comment] 2015-08-20 20:48
Thanks for response, Palourde!
Actually, it also happens with read-write user:
The following is the screen shot when I logged in with an admin user. If you look at the column "Datacenter", it overlapped the column "Version". 
I am not familiar with the GO web app framework, just thought is it possible to make the UI adjustable by end user, like user can drag and adjust the width of the column?
<img width="1259" alt="screen shot 2015-08-20 at 1 45 16 pm" src="https://cloud.githubusercontent.com/assets/2652627/9395176/c9e626dc-4741-11e5-815e-bf5fc312a87b.png">

Best Regards,
Autumn Wang

**Comment by palourde** [comment] 2015-08-31 16:37
@autumnw It looks I'm unable to reproduce the column overlapping issue, as you can see on the attached screenshot. Did you installed Uchiwa from the source or using the packages? Could you try to clear your browser cache and possibly try with an another browser?

![screen shot 2015-08-31 at 12 31 33](https://cloud.githubusercontent.com/assets/4105580/9583983/66579dbe-4fdc-11e5-94a6-6ffad26b5517.png)

**Comment by palourde** [comment] 2015-08-31 17:08
@hurrycaine The read-only user issue with the client view has been fixed with https://github.com/sensu/uchiwa-web/pull/63. It will be available in the next release.

**Comment by autumnw** [comment] 2015-08-31 18:47
Hi Simon,

I use the RPM package uchiwa-0.10.3-1.x86_64.rpm. So was it fixed in the
latest source code aleady?
Thanks again for your following up.

Regards,
Autumn Wang

On Mon, Aug 31, 2015 at 9:37 AM, Simon Plourde <notifications@github.com>
wrote:

> @autumnw <https://github.com/autumnw> It looks I'm unable to reproduce
> the column overlapping issue, as you can see on the attached screenshot.
> Did you installed Uchiwa from the source or using the packages? Could you
> try to clear your browser cache and possibly try with an another browser?
>
> [image: screen shot 2015-08-31 at 12 31 33]
> <https://cloud.githubusercontent.com/assets/4105580/9583983/66579dbe-4fdc-11e5-94a6-6ffad26b5517.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sensu/uchiwa/issues/368#issuecomment-136423683>.
>



-- 

[image: --]
汪 守金
[image: http://]about.me/shoujinwang
<http://about.me/shoujinwang>

**Comment by palourde** [comment] 2015-09-02 17:08
@autumnw It seems that this issue only affects datacenter names with underscore. The previous PR will fix this issue in the next release, meanwhile you can replace the underscore characters with dash characters.

**Closed** 2015-09-02 17:09 UTC
Labels: bug, frontend, high

**Comment by autumnw** [comment] 2015-09-02 17:44
That is great!
Thanks Simon!

Regards,
Autumn Wang.

On Wed, Sep 2, 2015 at 10:08 AM, Simon Plourde <notifications@github.com>
wrote:

> @autumnw <https://github.com/autumnw> It seems that this issue only
> affects datacenter names with underscore. The previous PR will fix this
> issue in the next release, meanwhile you can replace the underscore
> characters with dash characters.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sensu/uchiwa/issues/368#issuecomment-137173850>.
>



-- 

[image: --]
汪 守金
[image: http://]about.me/shoujinwang
<http://about.me/shoujinwang>
