### ISSUE TITLE
[BUG] when a proxy client has an unmatched token you can not click on the event or client to inspect

### ISSUE THREAD

**Issue by majormoses** [sensu/uchiwa#762] opened 2018-02-22 21:46 UTC
I was exploring token substitution with round robin proxy clients when the token is unmatched it returns a `Unmatched client token(s): es_cluster_name` but you can not click on it in events or clients.

![image](https://user-images.githubusercontent.com/3145127/36565783-6119006c-17d6-11e8-9fb5-a4ae74109cd7.png)

## Expected Behavior
I should be able to click on it to expand the error message so help triage and resolve it. In this case I know the problem but that will not always be true.

## Current Behavior
Unable to troubleshoot from uchiwa.

## Possible Solution
I realize this happens because the client does not exist...maybe we just allow it to pop up with the full event message?

## Steps to Reproduce (for bugs)
Add a proxy check with a source with a token that does not exist.

## Context
In this case I was able to fix the issue but in more complex issues it might be very hard to troubleshoot without looking at logs.

## Your Environment
* Uchiwa version used: 0.26.3
* Sensu version used: 1.2.1
* Operating System and version: Ubuntu 14.04 and 16.04

**Comment by majormoses** [comment] 2018-02-22 22:26
I see a similar issue even when it is correct and using `safe_mode` and the token not yet existing as it is still deploying/bootstrapping:

![image](https://user-images.githubusercontent.com/3145127/36567740-584a5fb6-17dc-11e8-97fc-354d98981345.png)

**Comment by portertech** [comment] 2018-02-22 23:14
@majormoses can you use a token default value (e.g. `:::token|default:::`) to cover this case until Uchiwa has a fix?

**Comment by majormoses** [comment] 2018-02-22 23:35
I'd honestly rather leave it in a broken state, unfortunately there is no good sane default. I'd rather it be ugly and in my face so I am motivated to pull in new changes for uchiwa once it is fixed. Safe mode at least saves us from getting an alert we can't do anything about.

**Comment by palourde** [comment] 2018-02-27 15:13
Hi @majormoses,

Unfortunately I was unable to reproduce this issue on the latest version of Uchiwa (1.1.3):

![unmatched_token](https://user-images.githubusercontent.com/4105580/36736474-b484f250-1ba6-11e8-9c0b-5b24d103a1d5.gif)

Can you see any relevant information in the browser's console? Otherwise, I would simply recommend you to try to upgrade to a more recent version of Uchiwa.

Thanks

**Comment by majormoses** [comment] 2018-02-27 17:11
@palourde I will try upgrading this is what I see in the console:
```
{"data":"404 Not Found\n","status":404,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"clients/:::es5.cluster.name:::?dc=Sensu","headers":{"Accept":"application/json, text/plain, */*","X-XSRF-TOKEN":"<REDACTED>"}},"statusText":"Not Found","xhrStatus":"complete"}
```

```
TypeError: Cannot read property 'history' of null
    at getCheck (controllers.js?rel=1507213640765:233)
    at controllers.js?rel=1507213640765:264
    at m.$digest (angular.js:18261)
    at m.$apply (angular.js:18531)
    at l (angular.js:12547)
    at s (angular.js:12785)
    at XMLHttpRequest.y.onload (angular.js:12702)
```

```

```

**Comment by majormoses** [comment] 2018-02-27 23:23
I can now click on the event but it gives me a 404 and says the client does not exist.

**Comment by palourde** [comment] 2018-03-23 15:16
So I just realized the token substitution was done for the `source` attribute, I missed that previously. I was able to reproduce it and turns out, Sensu API returns an empty client for that check:

![screen shot 2018-03-23 at 11 12 22 am](https://user-images.githubusercontent.com/4105580/37837282-394fb320-2e8b-11e8-8278-089f14847217.png)

I believe Sensu API should not return an empty client, and Uchiwa is obviously unable to retrieve this client when fetching the history, since it's an empty string.

Should we open an issue in Sensu @portertech?

**Comment by portertech** [comment] 2018-03-26 15:56
We should probably add a conditional to the result publisher (sensu-client) to remove `check[:source]` if empty, allowing the failed token sub event to be under the client's scope/context.

@palourde I'll add a Sensu Core issue for this.

**Comment by palourde** [comment] 2018-03-27 15:52
Closing this issue in favour of https://github.com/sensu/sensu/issues/1836.

**Closed by palourde** 2018-03-27 15:52 UTC
Labels: Bug, in progress
