### ISSUE TITLE
Feature request Remember the silenced alerts

### ISSUE THREAD

**Issue by jonasdaman** [sensu/uchiwa#473] opened 2016-04-12 07:45 UTC
Remember the silenced alerts after restart of uchiwa service.

**Comment by RiRa12621** [comment] 2016-04-23 18:48
stashed alerts should be a matter of your settings regarding redis, since they are not stored by uchiwa itself afaik

**Comment by palourde** [comment] 2016-05-23 21:05
Hi @jonasdaman 

As stated by Rick, the silence stashes are stored in Redis through the Sensu API so restarting Uchiwa does not have any effect on which alerts are silenced. If you think you are facing an issue where some events are not properly marked as silenced, please provide us more information, including steps to reproduce and possibly screenshots.

Thanks

**Closed by palourde** 2016-05-23 21:05 UTC
